import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import AdUnit from '../../../components/AdUnit';
import Sidebar from '../../../components/Sidebar';
import PostCard from '../../../components/PostCard';
import ImageCredit from '../../../components/ImageCredit';
import JsonLd from '../../../components/JsonLd';
import Prose from '../../../components/Prose';
import {
  formatDate,
  getAllPosts,
  getAllSlugs,
  getAllTopics,
  getPostBySlug,
  getRelatedPosts,
  renderMarkdown,
  splitHtmlForMidAd,
} from '../../../lib/posts';
import siteConfig from '../../../site.config.mjs';

/** Pre-render one static HTML file per markdown article. */
export function generateStaticParams() {
  return getAllSlugs().map((slug) => ({ slug }));
}

export function generateMetadata({ params }) {
  const post = getPostBySlug(params.slug);
  if (!post) return { title: 'Article not found' };

  const url = `/posts/${post.slug}`;
  return {
    title: post.title,
    description: post.description,
    keywords: post.keywords,
    alternates: { canonical: url },
    openGraph: {
      type: 'article',
      title: post.title,
      description: post.description,
      url,
      publishedTime: post.date,
      tags: post.keywords,
      images: post.image ? [{ url: post.image, width: 1200, height: 630, alt: post.title }] : undefined,
    },
    twitter: {
      card: 'summary_large_image',
      title: post.title,
      description: post.description,
      images: post.image ? [post.image] : undefined,
    },
  };
}

export default async function PostPage({ params }) {
  const post = getPostBySlug(params.slug);
  if (!post) notFound();

  const html = await renderMarkdown(post.content);
  const [firstHalf, secondHalf] = splitHtmlForMidAd(html);
  const related = getRelatedPosts(post, 3);
  const latest = getAllPosts()
    .filter((p) => p.slug !== post.slug)
    .slice(0, 6);
  const topics = getAllTopics().slice(0, 12);
  const canonical = `${siteConfig.url}/posts/${post.slug}`;

  return (
    <div className="container page">
      <div className="layout">
        <article>
          <header className="article-head">
            {post.topics[0] && (
              <p className="eyebrow">
                <Link href={`/topics/${post.topics[0].slug}`}>{post.topics[0].name}</Link>
              </p>
            )}

            {/* H1 — primary keyword target, generated by the AI pipeline */}
            <h1>{post.title}</h1>

            <div className="article-meta">
              <time dateTime={post.date}>{formatDate(post.date)}</time>
              <span aria-hidden="true">•</span>
              <span>{post.readingTime} min read</span>
              <span aria-hidden="true">•</span>
              <span>{post.author}</span>
            </div>

            {post.description && <p className="article-standfirst">{post.description}</p>}
          </header>

          {/* AD SLOT 1 — immediately below the post H1 title */}
          <AdUnit variant="below-title" />

          {post.image && (
            <figure className="article-hero">
              <Image
                src={post.image}
                alt={post.title}
                width={1200}
                height={675}
                sizes="(max-width: 1023px) 100vw, 760px"
                /* The hero is the LCP element, so it loads eagerly with high
                   fetch priority. Every other image on the page uses standard
                   lazy loading (see PostCard). Lazy-loading the LCP image is a
                   well-known PageSpeed regression, so it is deliberate here. */
                priority
              />
              {/* Photographer attribution, when the image came from Unsplash */}
              <ImageCredit name={post.imageCreditName} url={post.imageCreditUrl} />
            </figure>
          )}

          <Prose html={firstHalf} />

          {/* AD SLOT 2 — mid-way through the article body */}
          {secondHalf && <AdUnit variant="in-article" />}

          <Prose html={secondHalf} />

          {post.topics.length > 0 && (
            <ul className="tag-list" aria-label="Article topics" style={{ marginTop: 32 }}>
              {post.topics.map((topic) => (
                <li key={topic.slug}>
                  <Link href={`/topics/${topic.slug}`} className="tag">
                    {topic.name}
                  </Link>
                </li>
              ))}
            </ul>
          )}

          {post.sourceUrl && (
            <p className="source-note">
              <strong>Reporting reference:</strong> this briefing is {siteConfig.name}’s independent
              analysis. Primary reporting was published by{' '}
              {post.sourceName ? <strong>{post.sourceName}</strong> : 'the original outlet'} —{' '}
              <a href={post.sourceUrl} rel="nofollow noopener noreferrer" target="_blank">
                read the source article
              </a>
              .
            </p>
          )}

          {related.length > 0 && (
            <section className="related">
              <h2>Related analysis</h2>
              <div className="card-grid">
                {related.map((item) => (
                  <PostCard key={item.slug} post={item} />
                ))}
              </div>
            </section>
          )}

          <JsonLd
            data={{
              '@context': 'https://schema.org',
              '@type': 'NewsArticle',
              headline: post.title,
              description: post.description,
              datePublished: post.date,
              dateModified: post.date,
              image: post.image ? [post.image] : undefined,
              keywords: post.keywords.join(', '),
              inLanguage: 'en',
              mainEntityOfPage: { '@type': 'WebPage', '@id': canonical },
              author: { '@type': 'Organization', name: post.author },
              publisher: { '@type': 'Organization', name: siteConfig.name, url: siteConfig.url },
            }}
          />
        </article>

        {/* AD SLOT 3 — sticky sidebar rail (desktop only) */}
        <Sidebar latest={latest} topics={topics} heading="More briefings" />
      </div>
    </div>
  );
}
