#!/usr/bin/env node
/**
 * Post-build tasks for static hosting.
 *  - .nojekyll  : stops GitHub Pages from stripping /_next/* directories
 *  - CNAME      : custom domain, when CUSTOM_DOMAIN is set
 *  - ads.txt    : required by AdSense when NEXT_PUBLIC_ADSENSE_CLIENT is set
 *  - 404.html   : ensure a top-level 404 exists for GitHub Pages
 */
import fs from 'node:fs';
import path from 'node:path';

const OUT = path.join(process.cwd(), 'out');
if (!fs.existsSync(OUT)) {
  console.error('postbuild: ./out not found — did `next build` run?');
  process.exit(0);
}

fs.writeFileSync(path.join(OUT, '.nojekyll'), '');
console.log('postbuild: wrote .nojekyll');

const domain = process.env.CUSTOM_DOMAIN;
if (domain) {
  fs.writeFileSync(path.join(OUT, 'CNAME'), `${domain}\n`);
  console.log(`postbuild: wrote CNAME (${domain})`);
}

const adsenseClient = process.env.NEXT_PUBLIC_ADSENSE_CLIENT;
if (adsenseClient) {
  const publisherId = adsenseClient.replace(/^ca-/, '');
  fs.writeFileSync(path.join(OUT, 'ads.txt'), `google.com, ${publisherId}, DIRECT, f08c47fec0942fa0\n`);
  console.log('postbuild: wrote ads.txt');
}

// _headers : Cloudflare Pages cache policy.
// HTML must never be cached by the CDN edge or the browser. Pages embed their
// CSS inline and reference hashed /_next/ assets, so a stale HTML document is
// the one thing that can render a page wrong. Hashed assets are immutable and
// safe to cache for a year.
const headers = `# Generated by scripts/postbuild.mjs — do not edit by hand.

/_next/static/*
  Cache-Control: public, max-age=31536000, immutable

/images/*
  Cache-Control: public, max-age=86400

# Correct content types for the SEO/PWA files. Cloudflare Pages guesses
# application/octet-stream for .webmanifest, which makes browsers ignore it.
/site.webmanifest
  Content-Type: application/manifest+json; charset=utf-8
  Cache-Control: public, max-age=86400

/sitemap.xml
  Content-Type: application/xml; charset=utf-8
  Cache-Control: public, max-age=3600

/rss.xml
  Content-Type: application/rss+xml; charset=utf-8
  Cache-Control: public, max-age=3600

/*.html
  Cache-Control: public, max-age=0, must-revalidate

/*
  Cache-Control: public, max-age=0, must-revalidate
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: SAMEORIGIN
`;
fs.writeFileSync(path.join(OUT, '_headers'), headers);
console.log('postbuild: wrote _headers');

const nested404 = path.join(OUT, '404', 'index.html');
const root404 = path.join(OUT, '404.html');
if (fs.existsSync(nested404) && !fs.existsSync(root404)) {
  fs.copyFileSync(nested404, root404);
  console.log('postbuild: wrote 404.html');
}
